#!/bin/bash -e
# set hostname
# HOSTNAME: the name (if none specified, nothing is done)
#
# The rename itself is lib/hostname.sh, shared with 31fqdn.

INITHOOKS_DEFAULT="${INITHOOKS_DEFAULT:-/etc/default/inithooks}"
# shellcheck source=default/inithooks
source "$INITHOOKS_DEFAULT"
# shellcheck source=lib/hostname.sh
source "$INITHOOKS_PATH/lib/hostname.sh"

if [[ -e "$INITHOOKS_CONF" ]]; then
    # shellcheck source=/dev/null
    source "$INITHOOKS_CONF"
fi

[[ -z "$HOSTNAME" ]] && exit 0

hostname_set "$HOSTNAME"

exit 0
