#!/usr/bin/env bats
# Tests for bin/keel-host-keys (keel-core#8).
#
# SSH keys are generated by the real ssh-keygen into a scratch directory, so
# the fingerprints and modes asserted are the program's own. The TLS and
# snakeoil generators write to fixed paths under /etc, so turnkey-make-ssl-cert
# and make-ssl-cert are stubs that write a real key with openssl where the
# script is pointed, and logger is a stub the tests read.

bats_require_minimum_version 1.5.0

load helpers

REPO=$BATS_TEST_DIRNAME/..
SCRIPT=$REPO/bin/keel-host-keys

setup() {
    setup_stubs
    stub logger

    export SSH_DIR=$BATS_TEST_TMPDIR/etc/ssh
    export TLS_KEY=$BATS_TEST_TMPDIR/etc/ssl/private/cert.key
    export TLS_PEM=$BATS_TEST_TMPDIR/etc/ssl/private/cert.pem
    export SNAKEOIL_KEY=$BATS_TEST_TMPDIR/etc/ssl/private/ssl-cert-snakeoil.key
    export SNAKEOIL_CERT=$BATS_TEST_TMPDIR/etc/ssl/certs/ssl-cert-snakeoil.pem
    export SHARED_HOST_KEYS=$BATS_TEST_TMPDIR/shared-host-keys
    mkdir -p "$SSH_DIR" "$(dirname "$TLS_KEY")" "$(dirname "$SNAKEOIL_CERT")"
    printf '# none\n' > "$SHARED_HOST_KEYS"

    # the generators write a fresh key where the script reads it, the way
    # the real ones write /etc/ssl/private
    stub turnkey-make-ssl-cert "openssl genpkey -algorithm ed25519 -out '$TLS_KEY' 2>/dev/null
cat '$TLS_KEY' > '$TLS_PEM'"
    stub make-ssl-cert "openssl genpkey -algorithm ed25519 -out '$SNAKEOIL_KEY' 2>/dev/null
echo cert > '$SNAKEOIL_CERT'"
}

# ssh_fp FILE: the SHA256 fingerprint of a public key file
ssh_fp() {
    ssh-keygen -lf "$1" -E sha256 | cut -d ' ' -f 2
}

# tls_digest FILE: the digest the script compares, of the public half
tls_digest() {
    openssl pkey -in "$1" -pubout -outform DER 2>/dev/null | sha256sum | cut -d ' ' -f 1
}

all_ssh_keys() {
    local t
    for t in rsa ecdsa ed25519; do
        ssh-keygen -q -t "$t" -N '' -f "$SSH_DIR/ssh_host_${t}_key"
    done
}

tls_pair() {
    openssl genpkey -algorithm ed25519 -out "$TLS_KEY" 2>/dev/null
    cat "$TLS_KEY" > "$TLS_PEM"
}

@test "generates the three SSH host keys a machine has none of" {
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    for t in rsa ecdsa ed25519; do
        [ -f "$SSH_DIR/ssh_host_${t}_key" ]
        [ -f "$SSH_DIR/ssh_host_${t}_key.pub" ]
        [ "$(stat -c %a "$SSH_DIR/ssh_host_${t}_key")" = 600 ]
        ssh-keygen -lf "$SSH_DIR/ssh_host_${t}_key.pub" >/dev/null
    done
    [[ "$(calls logger)" == *"generated SSH host key"* ]]
}

@test "leaves SSH host keys of its own untouched" {
    all_ssh_keys
    before=$(cat "$SSH_DIR"/ssh_host_*)
    tls_pair
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(cat "$SSH_DIR"/ssh_host_*)" = "$before" ]
    [[ "$(calls logger)" != *ssh_host_* ]]
}

@test "replaces an SSH host key that is on the shared list, and says so" {
    all_ssh_keys
    tls_pair
    shared=$(ssh_fp "$SSH_DIR/ssh_host_ed25519_key.pub")
    rsa_before=$(ssh_fp "$SSH_DIR/ssh_host_rsa_key.pub")
    printf 'ssh %s published in the core layer\n' "$shared" >> "$SHARED_HOST_KEYS"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(ssh_fp "$SSH_DIR/ssh_host_ed25519_key.pub")" != "$shared" ]
    [ "$(ssh_fp "$SSH_DIR/ssh_host_rsa_key.pub")" = "$rsa_before" ]
    [[ "$(calls logger)" == *warning*"shared"*"ssh_host_ed25519_key"* ]]
}

@test "regenerates a key whose public half is missing" {
    all_ssh_keys
    tls_pair
    rm "$SSH_DIR/ssh_host_ecdsa_key.pub"
    old=$(cat "$SSH_DIR/ssh_host_ecdsa_key")
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ -f "$SSH_DIR/ssh_host_ecdsa_key.pub" ]
    [ "$(cat "$SSH_DIR/ssh_host_ecdsa_key")" != "$old" ]
}

@test "fails when ssh-keygen cannot make a key" {
    stub ssh-keygen 'exit 1'
    tls_pair
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"ssh_host_"* ]]
}

@test "generates the TLS key and certificate when there are none" {
    all_ssh_keys
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls turnkey-make-ssl-cert)" = "--default --force" ]
    [ -f "$TLS_KEY" ]
}

@test "generates the TLS pair when only the combined file is missing" {
    all_ssh_keys
    tls_pair
    rm "$TLS_PEM"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls turnkey-make-ssl-cert)" = "--default --force" ]
}

@test "leaves a TLS key of its own untouched" {
    all_ssh_keys
    tls_pair
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ -z "$(calls turnkey-make-ssl-cert)" ]
}

@test "replaces the TLS key when it is the shared one" {
    all_ssh_keys
    tls_pair
    shared=$(tls_digest "$TLS_KEY")
    printf 'tls %s turnkey-ssl\n' "$shared" >> "$SHARED_HOST_KEYS"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls turnkey-make-ssl-cert)" = "--default --force" ]
    [ "$(tls_digest "$TLS_KEY")" != "$shared" ]
    [[ "$(calls logger)" == *warning*"shared"*"cert.key"* ]]
}

@test "replaces the TLS pair when only the combined file holds the shared key" {
    all_ssh_keys
    tls_pair
    openssl genpkey -algorithm ed25519 -out "$BATS_TEST_TMPDIR/shared.key" 2>/dev/null
    printf -- '-----BEGIN CERTIFICATE-----\nMIIB\n-----END CERTIFICATE-----\n' > "$TLS_PEM"
    cat "$BATS_TEST_TMPDIR/shared.key" >> "$TLS_PEM"
    printf 'tls %s turnkey-ssl\n' "$(tls_digest "$BATS_TEST_TMPDIR/shared.key")" >> "$SHARED_HOST_KEYS"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls turnkey-make-ssl-cert)" = "--default --force" ]
    [[ "$(calls logger)" == *warning*"cert.pem"* ]]
}

@test "fails when the TLS generator is not installed and a key is needed" {
    all_ssh_keys
    rm "$STUBS/turnkey-make-ssl-cert"
    PATH=$STUBS:/usr/bin:/bin run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"turnkey-make-ssl-cert"* ]]
}

@test "fails when the TLS generator leaves the shared key in place" {
    all_ssh_keys
    tls_pair
    printf 'tls %s turnkey-ssl\n' "$(tls_digest "$TLS_KEY")" >> "$SHARED_HOST_KEYS"
    cp "$TLS_KEY" "$BATS_TEST_TMPDIR/shared.key"
    stub turnkey-make-ssl-cert "cp '$BATS_TEST_TMPDIR/shared.key' '$TLS_KEY'
cp '$BATS_TEST_TMPDIR/shared.key' '$TLS_PEM'"
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"cert.key"* ]]
}

@test "does nothing for snakeoil where ssl-cert is not installed" {
    all_ssh_keys
    tls_pair
    rm "$STUBS/make-ssl-cert"
    PATH=$STUBS:/usr/bin:/bin run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ ! -e "$SNAKEOIL_KEY" ]
}

@test "generates the snakeoil pair where ssl-cert is installed and it is missing" {
    all_ssh_keys
    tls_pair
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls make-ssl-cert)" = "generate-default-snakeoil --force-overwrite" ]
    [ -f "$SNAKEOIL_KEY" ]
}

@test "leaves a snakeoil pair of its own untouched" {
    all_ssh_keys
    tls_pair
    openssl genpkey -algorithm ed25519 -out "$SNAKEOIL_KEY" 2>/dev/null
    echo cert > "$SNAKEOIL_CERT"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ -z "$(calls make-ssl-cert)" ]
}

@test "replaces a snakeoil key that is on the shared list" {
    all_ssh_keys
    tls_pair
    openssl genpkey -algorithm ed25519 -out "$SNAKEOIL_KEY" 2>/dev/null
    echo cert > "$SNAKEOIL_CERT"
    shared=$(tls_digest "$SNAKEOIL_KEY")
    printf 'tls %s ssl-cert in the postgresql layer\n' "$shared" >> "$SHARED_HOST_KEYS"
    run "$SCRIPT"
    [ "$status" -eq 0 ]
    [ "$(calls make-ssl-cert)" = "generate-default-snakeoil --force-overwrite" ]
    [ "$(tls_digest "$SNAKEOIL_KEY")" != "$shared" ]
}

@test "fails without the list of shared keys, after generating what is missing" {
    rm "$SHARED_HOST_KEYS"
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [ -f "$SSH_DIR/ssh_host_ed25519_key" ]
    [[ "$(calls logger)" == *err*"shared-host-keys"* ]]
}

@test "the packaged list of shared keys is well formed" {
    run awk '!/^[[:space:]]*(#|$)/ && !(($1 == "ssh" && $2 ~ /^SHA256:[A-Za-z0-9+\/]{43}$/) || ($1 == "tls" && $2 ~ /^[0-9a-f]{64}$/)) { print; bad = 1 } END { exit bad }' \
        "$REPO/shared-host-keys"
    [ "$status" -eq 0 ]
    grep -q -v -E '^[[:space:]]*(#|$)' "$REPO/shared-host-keys"
}

@test "fails when make-ssl-cert fails" {
    all_ssh_keys
    tls_pair
    stub make-ssl-cert 'exit 1'
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"ssl-cert-snakeoil.key"* ]]
}

@test "fails when make-ssl-cert reports success and writes no key" {
    all_ssh_keys
    tls_pair
    stub make-ssl-cert 'exit 0'
    run "$SCRIPT"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"ssl-cert-snakeoil.key"*"missing or still shared"* ]]
}

@test "fails, not skips, when the key directory cannot be written" {
    chmod 555 "$SSH_DIR"
    tls_pair
    run "$SCRIPT"
    chmod 755 "$SSH_DIR"
    [ "$status" -ne 0 ]
    [[ "$(calls logger)" == *err*"ssh_host_"* ]]
}

@test "a generator writes its files with no access for group or others" {
    all_ssh_keys
    stub turnkey-make-ssl-cert "touch '$TLS_KEY' '$TLS_PEM'
openssl genpkey -algorithm ed25519 2>/dev/null > '$TLS_KEY'
cat '$TLS_KEY' > '$TLS_PEM'"
    run env -u UMASK bash -c "umask 022; '$SCRIPT'"
    [ "$status" -eq 0 ]
    [ "$(stat -c %a "$TLS_KEY")" = 600 ]
    [ "$(stat -c %a "$TLS_PEM")" = 600 ]
}
