default/*                               /etc/default
bin/*                                   /usr/lib/inithooks/bin
firstboot.d/*                           /usr/lib/inithooks/firstboot.d
everyboot.d/*                           /usr/lib/inithooks/everyboot.d
lib/*                                   /usr/lib/inithooks/lib
run                                     /usr/lib/inithooks
rsyslog.d/*                             /etc/rsyslog.d
update-motd.d/*                         /etc/update-motd.d

turnkey-init-fence/htdocs               /usr/lib/inithooks/turnkey-init-fence

keel-init                               /usr/sbin
turnkey-init                            /usr/sbin
turnkey-sudoadmin                       /usr/sbin
turnkey-install-security-updates        /usr/sbin
shared-host-keys                        /usr/lib/inithooks
systemd/postgresql@.service.d/keel-host-keys.conf /usr/lib/systemd/system/postgresql@.service.d
