#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
    for service in inithooks turnkey-init-fence; do
        if systemctl is-active -q "$service.service"; then
            touch "/run/$service-was-active"
        fi
    done
fi

#DEBHELPER#

exit 0
